#!/bin/bash

# Source: https://gist.github.com/jordan-brough/48e2803c0ffa6dc2e0bd

# Interactive prompt for most recent 4 branches:
#   $ git recent -n 5
#   1) master  4) deleted-branch
#   2) stable  5) improve-everything
#   3) fun
#   Choose a branch: 2

# List mode (non-interactive):
#   $ git recent -n 5 -l
#   master
#   stable
#   fun
#   deleted-branch
#   improve-everything


git-recent() {
  while getopts "hn:" opt; do
    case $opt in
      h)
        usage
        exit 1
        ;;
      n)
        NUM=$OPTARG
        ;;
      \?)
        usage
        exit 1
        ;;
    esac
  done

  NUM=${NUM-10} # default to 10 lines

  # This: `awk ' !x[$0]++'` removes duplicates.  See http://stackoverflow.com/questions/11532157
  UNIQUE_BRANCHES=$(git reflog | egrep -io "moving from ([^[:space:]]+)" | awk '{ print $3 }' | awk ' !x[$0]++')

  # Exclude branches that don't exist locally
  BRANCH_CHOICES=( $(echo "$UNIQUE_BRANCHES" | while read line; do
    git rev-parse --verify "$line" &>/dev/null && echo "$line"
  done | head -n "$NUM") )

  PS3="Choose a branch: "
  select d in "${BRANCH_CHOICES[@]}"; do test -n "$d" && break; echo ">>> Invalid Selection"; done

  git checkout "$d"
}
